# File: .github/workflows/publish.yml
name: Publish Package to PyPI

on:
  push:
    # Trigger only on tags starting with 'v' (e.g. v1.0.0)
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip and Install Build Tools
        run: |
          python -m pip install --upgrade pip
          # Install your build tool "uv" and twine for uploading
          pip install uv twine

      - name: Build Distribution Packages
        run: uv build

      - name: Publish to PyPI
        env:
          # The default username for API token authentication is __token__
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
